# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20160705_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgoFloats',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('catalog.dataset',),
        ),
    ]
